services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=user_authentication
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=verYs3cret
    ports:
      - '5432'
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"